# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
cache: cocoapods
before_install:
  - rvm install ruby-2.2.2 # Required by Cocoapods gem dependencies
  - rvm use ruby-2.2.2 
  - gem install cocoapods --no-document # Since Travis is not always on latest version
  - gem install xcpretty --no-document
  - chmod +x tests.sh
script:
  - set -o pipefail && ./tests.sh
  - pod lib lint
